library super_box;
// -----------------------------------------------------------------------------
import 'package:flutter/material.dart';
import 'src/a_the_box_of_super_box/x_the_box_of_super_box.dart';
import 'src/b_super_box_child/x_super_box_child.dart';
import 'src/c_super_box_contents/x_super_box_contents.dart';
import 'src/d_super_box_highlights/x_box_highlight.dart';
import 'src/e_super_box_gradient/x_box_gradient.dart';
import 'src/f_super_box_tap_layer/x_tap_layer.dart';
import 'src/x_controllers/z_helper_methods.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
// -----------------------------------------------------------------------------
/// SUPER BOX
part './src/a_the_super_box.dart';
// --------------------
/// CONTROLLER
part './src/x_controllers/xxx_super_box_controller.dart';
// --------------------
/// LOADING
part './src/c_super_box_contents/x_loading.dart';
// -----------------------------------------------------------------------------
